/colossus_publisher:
  ros__parameters:
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    radar_ip: 10.77.2.211
    radar_port: 6317
    use_sim_time: false
