/laser_scan_publisher:
  ros__parameters:
    end_azimuth: 399
    end_bin: 2855
    power_threshold: 110
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    radar_ip: 10.77.2.211
    radar_port: 6317
    start_azimuth: 0
    start_bin: 0
    use_sim_time: false
