/camera_publisher:
  ros__parameters:
    camera_url: rtsp://admin:Navtech Radar.1@10.77.3.103:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
